name: laxtop
description: Application to connect suppliers easier

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ">=2.10.5 <3.0.0"

# http, flutter_svg, cupertino_icons, intl can not be upgraded for now
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  flutter_svg: ^0.19.1
  permission:
    git:
      url: https://github.com/kamlesh9070/permission
  path_provider: ^1.6.27
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.0+1
  google_maps_flutter: ^1.2.0
  image_picker: ^0.6.7+22
  url_launcher: ^5.7.10
  intl: ^0.16.1
  font_awesome_flutter: ^8.11.0
  rxdart: ^0.25.0
  json_annotation: ^3.1.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  package_info: ^0.4.3+4
  super_enum: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  hive_generator: ^0.8.2
  super_enum_generator: ^0.6.0
  analyzer: ^0.41.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/file.svg
    - assets/reorder_hint.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
